export const suggestions = [
  "Bananas 🍌",
  "Apples 🍎🍏",
  "Grapes 🍇",
  "Pears 🍐",
  "Watermelon 🍉",
  "Melon 🍈",
  "Orange 🍊",
  "Lemon 🍋",
  "Clementine 🍊",
  "Avocado 🥑",
  "Salad Leaves 🥗",
  "Tomatos 🍅",
  "Cucumber 🥒",
  "Eggplants 🍆",
  "Zucchini",
  "Cauliflower 🥦",
  "Cabbage 🥬",
  "Carrots 🥕",
  "Onions",
  "Garlic",
  "Mushroom 🍄",
  "Peas",
  "Fowl Beans 🥫",
  "Beans 🥫",
  "Tomato Sauce",
  "Milk 🥛",
  "Yogurt",
  "Meat 🥩",
  "Chicken 🍗",
  "Ground Meat",
  "Eggs 🥚",
  "Cheese 🧀",
  "Spread Cheese 🧀",
  "",
  "",
  "Cini Minis 🥣",
  "Bread 🍞",
  "Pita Bread",
  "Crunchies",
  "Rice 🍚",
  "Pasta",
  "Oil",
  "Salt 🧂",
  "Black Papper",
  "Chocolate  🍫",
  "Candies 🍬",
  "Sparkling Water",
  "Coffee ☕",
  "Toiler Papers 🧻",
  "Tissues 🤧"
];
